name: Test and Lint
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  IS_ENTERPRISE: ${{ github.server_url != 'https://github.com' }}

jobs:
  # Job A: Runs ONLY on GitHub-hosted Ubuntu (regular GitHub)
  test-ubuntu:
    runs-on: ubuntu-22.04
    if: ${{ !env.IS_ENTERPRISE }}  # Explicit environment check
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Test
      #   run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # - name: Lint
      #   run: docker compose run --rm app sh -c "flake8"
      - name: Echo
        run: echo "Hello, Ubuntu!"

  # Job B: Runs ONLY on self-hosted Windows (GitHub Enterprise)
  test-windows:
    runs-on: [self-hosted, Windows]
    if: ${{ env.IS_ENTERPRISE }}  # Explicit environment check
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  # Final Status Check (Environment-aware)
  final-status:
    needs: [test-ubuntu, test-windows]
    runs-on: ${{ env.IS_ENTERPRISE && 'self-hosted' || 'ubuntu-22.04' }}
    if: always()
    steps:
      - name: Evaluate Results
        run: |
          if [[ "${{ needs.test-ubuntu.result }}" == "success" ]] || 
             [[ "${{ needs.test-windows.result }}" == "success" ]]; then
            echo "Workflow Succeeded"
            exit 0
          else
            echo "Workflow Failed"
            exit 1
          fi