name: Test and Lint
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  # Try Ubuntu runner first
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-22.04
    timeout-minutes: 1  # Limit wait time to 1 minute
    if: success() || failure()  # Run regardless of other jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  # Try Windows runner as alternative
  test-windows:
    name: Test on Windows
    runs-on: [self-hosted, Windows]
    timeout-minutes: 1  # Limit wait time to 1 minute
    if: success() || failure()  # Run regardless of other jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  # Final job to determine overall workflow success
  final-status:
    needs: [test-ubuntu, test-windows]
    runs-on: [ubuntu-22.04, Windows, self-hosted]
    if: always()
    steps:
      - name: Final Status
        run: |
          if [[ "${{ needs.test-ubuntu.result }}" == "success" || "${{ needs.test-windows.result }}" == "success" ]]; then
            exit 0
          else
            exit 1
          fi