name: Test and Lint
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  # Job A: Runs ONLY on regular GitHub (Ubuntu Runner)
  test-ubuntu:
    runs-on: ubuntu-22.04
    if: ${{ github.server_url == 'https://github.com' }}  # Directly check server URL
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Echo
        run: echo "Hello from Ubuntu!"
      # - name: Test
      #   run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # - name: Lint
      #   run: docker compose run --rm app sh -c "flake8"

  # Job B: Runs ONLY on GitHub Enterprise (Self-Hosted Windows Runner)
  test-windows:
    runs-on: [self-hosted, Windows]
    if: ${{ github.server_url != 'https://github.com' }}  # Directly check server URL
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  # Final Status Check
  final-status:
    needs: [test-ubuntu, test-windows]
    runs-on: ubuntu-22.04  # You can adjust this as needed
    if: always()
    steps:
      - name: Evaluate Results
        run: |
          echo "Evaluating job results..."
          # Initialize overall result as success
          OVERALL_RESULT="success"

          # Check if test-ubuntu job ran and its result
          if [ "${{ needs.test-ubuntu.result }}" == "failure" ]; then
            echo "test-ubuntu failed."
            OVERALL_RESULT="failure"
          fi

          # Check if test-windows job ran and its result
          if [ "${{ needs.test-windows.result }}" == "failure" ]; then
            echo "test-windows failed."
            OVERALL_RESULT="failure"
          fi

          echo "Overall result: $OVERALL_RESULT"
          if [ "$OVERALL_RESULT" == "success" ]; then
            exit 0
          else
            exit 1
          fi
